---
driver:
  name: ec2
  region: us-west-2
  instance_type: t2.small # m4.2xlarge
  key_name: MyKeyPair
 
transport: 
  ssh_key:  ~/.ssh/MyKeyPair.pem 

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    image_id: ami-746aba14

suites:
  - name: default
    run_list:
      - recipe[pixinsight-aws::default]
    attributes:
